name: Release

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  build-deb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install build tools
        run: sudo apt-get update && sudo apt-get install -y build-essential dpkg-dev
      - name: Configure
        run: ./configure
      - name: Build Debian package
        run: make deb VERSION=${{ github.event.release.tag_name }}
      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./Concreto.deb
          asset_name: Concreto.deb
          asset_content_type: application/vnd.debian.binary-package

